### ISSUE TITLE
Change Base Font

### ISSUE THREAD

**Issue by cSDes1gn** [LEAP-Systems/LEAP-Systems.github.io#6]
Im not satisfied with the current font we are using. I did some browsing and I've narrowed it down to these:
 - [Josefin Sans](https://fonts.google.com/specimen/Josefin+Sans?preview.text=LEAP%20SYSTEMS&preview.text_type=custom&preview.size=61&category=Serif,Sans+Serif,Display,Monospace&query=Josefin+Sans) Body text
 - [Libre Barcode 39 Text](https://fonts.google.com/specimen/Libre+Barcode+39+Text?preview.text=LEAP%20SYSTEMS&preview.text_type=custom&preview.size=61&category=Serif,Sans+Serif,Display,Monospace&query=Libre+Barcode) For Menu and Header Text

Play around with these and let me know what you like

**Comment by BrandonLucasZhu** [comment]
Not all of these have wide support browser capabilities. We need a font package that has woff2, woff, ttf, eot, and svg(mobile) formats.

**Comment by cSDes1gn** [comment]
Are we able to get those font packages?
