### ISSUE TITLE
Title Text

### ISSUE THREAD

**Issue by cSDes1gn** [LEAP-Systems/LEAP-Systems.github.io#7]
The title page should probably say: "Light Emitting Access Point Project". We are really aiming to recruit people with this website so the title should be direct.

**Comment by BrandonLucasZhu** [comment]
Do you want this to be at the welcoming page? Take a look at it when you can. Just did a recent update.

**Comment by cSDes1gn** [comment]
Yea I saw it I can see text now which is good lol
